apiVersion: v1
kind: Secret
metadata:
  name: ofertonazos-secrets
  labels:
    app: ofertonazos
type: Opaque
stringData:
  NEXT_PUBLIC_SUPABASE_URL: "https://fbxwdtujxekpfsbdnjcg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieHdkdHVqeGVrcGZzYmRuamNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1ODMwNDIsImV4cCI6MjA4ODE1OTA0Mn0.VFX8ghJLSEMTfk5v_XMKiRBMlfempak9L6nNfARMIkA"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieHdkdHVqeGVrcGZzYmRuamNnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjU4MzA0MiwiZXhwIjoyMDg4MTU5MDQyfQ.vAtge9W8K2-DPIXNjAPMbUVy5WMZYCyBzB8l2YY3UpM"
  API_SECRET_KEY: "86c94f2327a86612726d965b931746f32b78aaeb975dc482537a2dc0e40e3ed3"
