apiVersion: v1
kind: Service
metadata:
  name: ofertonazos
  labels:
    app: ofertonazos
spec:
  type: NodePort
  selector:
    app: ofertonazos
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
