apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ofertonazos
  labels:
    app: ofertonazos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ofertonazos.local   # for Minikube; change to real domain in production
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ofertonazos
                port:
                  number: 80
