apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ofertonazos.fullname" . }}-secrets
  labels:
    {{- include "ofertonazos.labels" . | nindent 4 }}
type: Opaque
data:
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secrets.supabaseServiceRoleKey | b64enc | quote }}
  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey | b64enc | quote }}
